name: comp2300-pipeline
on: [push, pull_request]

jobs:
  file_main:
    name: "file:main (filecheck)"
    runs-on: ubuntu-latest
    container:
      image: comp23002024/comp2300-microbit-test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate src/main.S exists
        run: python3 /scripts/validate.py exists src/main.S

      - name: Validate src/main.S differs from reference
        run: python3 /scripts/validate.py different src/main.S -F /data/base/a2/main.S

  build_main:
    name: "build:main (build)"
    runs-on: ubuntu-latest
    needs: [file_main]
    container:
      image: comp23002024/comp2300-microbit-test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build with make
        run: |
          make ARM_PREFIX="" CC=arm-none-eabi-gcc LD=arm-none-eabi-ld OBJCOPY=arm-none-eabi-objcopy

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            program.elf
            program.bin
          if-no-files-found: ignore

  report:
    name: "report (filecheck)"
    runs-on: ubuntu-latest
    needs: [file_main]
    container:
      image: comp23002024/comp2300-microbit-test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate README.md
        run: |
          python3 /scripts/validate.py exists README.md
          python3 /scripts/validate.py word-count README.md assignment-2

  pdf:
    name: "pdf (render)"
    runs-on: ubuntu-latest
    needs: [report]
    container:
      image: comp23002024/comp2300-md2pdf:latest
    env:
      PDF_NAME: assignment-2.pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: List files
        run: ls -la

      - name: Create placeholder files if missing
        run: |
          touch references.md
          mkdir -p src
          touch src/main.S

      - name: Echo ENV Vars
        run: |
          echo "$PDF_NAME"
          echo "REFERENCES:"
          cat references.md || true

      - name: Generate PDF
        run: |
          chmod +x /data/generate_report_a2.sh || true
          /data/generate_report_a2.sh

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: assignment-2-pdf
          path: ${{ env.PDF_NAME }}
          if-no-files-found: error
